---
hostname: team2-p1
management_ip: 192.168.122.30/24

interfaces_BB:
    - name: ge-0/0/0
      description: ---- VERS PE1 ----
      ip: 192.168.124.0
      mask: 31
      metric: 1
      peer_name: PE1 
      peer_port: ge-0/0/0 

    - name: ge-0/0/1
      description: ---- VERS PE2 ----
      ip: 192.168.124.2
      mask: 31
      metric: 1
      peer_name: PE2
      peer_port: ge-0/0/0

    - name: ge-0/0/2
      description: ---- VERS PE3 ----
      ip: 192.168.124.4
      mask: 31
      metric: 1
      peer_name: PE3
      peer_port: ge-0/0/0


    - name: ge-0/0/3
      description: ---- VERS PE4 ----
      ip: 192.168.124.6
      mask: 31
      metric: 1
      peer_name: PE4
      peer_port: ge-0/0/0


host:
    ip_loopback: 10.1.1.1
    description: ---- ADMINISTRATION ET SERVICES ----
    mask: 32
    iso: 49.0001.0000.0000.0030.00

bgp:
    local:
        cluster: 10.1.1.1
    rr_bgp: [ 10.2.1.1, 10.2.2.1, 10.2.3.1, 10.2.4.1 ]

ldp:
    neighbor: [ 192.168.124.1, 192.168.124.3, 192.168.124.5, 192.168.124.7 ]
